# Generated by Django 2.0.5 on 2018-06-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180609_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.Unit'),
            preserve_default=False,
        ),
    ]
