# Generated by Django 2.0.5 on 2018-06-04 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20180521_1907'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(1, 'WAITING_FOR_VALIDATION'), (2, 'WAITING_FOR_IMPLEMENTATION'), (3, 'WAITING_FOR_APPROVAL'), (4, 'REFUSED'), (5, 'COMPLETED')], default=0, max_length=1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('headline', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('proposal', models.TextField()),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('validation_text', models.TextField()),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('standard_update_due_date', models.DateTimeField(blank=True, null=True)),
                ('implementation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_approver', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('implementer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_implementer', to=settings.AUTH_USER_MODEL)),
                ('mailing_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_mailing_list', to='account.Unit')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_validator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
