# Generated by Django 2.0.5 on 2018-06-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180607_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='validator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_validator', to='account.Employee'),
        ),
    ]
