# Generated by Django 2.0.5 on 2018-07-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20180630_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='standard_update_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
