# Generated by Django 2.0.5 on 2018-07-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_approval_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approval_choice',
        ),
        migrations.AddField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[(1, 'WAITING_FOR_VALIDATION'), (2, 'WAITING_FOR_IMPLEMENTATION'), (3, 'WAITING_FOR_APPROVAL'), (4, 'COMPLETED'), (5, 'REFUSED')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='validation_choice',
            field=models.CharField(choices=[(1, 'WAITING_FOR_VALIDATION'), (2, 'WAITING_FOR_IMPLEMENTATION'), (3, 'WAITING_FOR_APPROVAL'), (4, 'COMPLETED'), (5, 'REFUSED')], default=5, max_length=1),
        ),
    ]
